version: 2
project_name: oda-lite

release:
  prerelease: false
  draft: false
  extra_files:
    - glob: release/**/*.tar.gz
    - glob: release/**/*.sha256

changelog:
  sort: desc
  use: github

# No builds aquí; adjuntamos ficheros ya generados mediante release.extra_files
